### ISSUE TITLE
Defacing issue

### ISSUE THREAD

**Issue by RRouhi** [SynthRAD2023/preprocessing#3]
Thank you for sharing the interesting work. I'm going to use anonymize.py to deface some MR images in Nifti format. There are two functions I need to use for defacing the images: detect_face(args.ref, args.i, args.o) and remove_face(args.mask, args.ref, args.o, background=-1000). I'm wondering what should be the reference images needed for these two functions. Could you please guide me on how I can do the defaced images?

Rahimeh

**Comment by matteomaspero** [comment]
Hi Rahimeh,

This function is meant to be used on CT (that's why the background is set to -1000).

I hope this helps. If you need to deface MRI there are some examples in the literature, on CBCT it is a bit more difficult. We decided to use CT since this is the reference image for both the tasks.

I hope this would help you further.

Good luck with the defacing.

Matteo
